### ISSUE TITLE
Bug - multiple queues in --queue parameter

### ISSUE THREAD

**Issue by arxeiss** [orobogenius/sansdaemon#1]
There is a bug if you are running multiple queues by parameter `--queue`. Non of them runs. Check here [Heading 'Queue Priorities'](https://laravel.com/docs/5.6/queues#running-the-queue-worker)

PR is prepared: #2 

But otherwise, it is amazing peace of work. Thank you so much, saved me lots of curse....

**Comment by orobogenius** [comment]
Nice catch @arxeiss, that was an oversight on my part. I have reviewed the codes and it's as you said, when the `--queue` parameter is used and a *comma-delimited* list is specified, the jobs don't run.

I'm glad I've been able to save you lots of curses. 😄
