### ISSUE TITLE
Laravel 6.0 - error in constructor

### ISSUE THREAD

**Issue by BartoszWoszczak** [orobogenius/sansdaemon#12]
`Too few arguments to function Illuminate\Queue\Console\WorkCommand::__construct(), 1 passed in ../vendor/queueworker/sansdaemon/src/Console/WorkCommand.php on line 37 and exactly 2 expected  `

Need cache extra paramater in constructor :)

**Comment by CodeLieutenant** [comment]
Laravel 6.0 support was added with #11  pull request, fixing this issue
