### ISSUE TITLE
Love this package

### ISSUE THREAD

**Issue by garhbod** [orobogenius/sansdaemon#14]
I was using a scheduled job to check if `queue:work` was still running but I'm sure you probably already know that doesn't work the best. With this package is a god send. Just set the below and it's pretty close to `queue:work` running continuously

```
$schedule->command(
    'queue:work --timeout=80 --sleep=3 --tries=5 --sansdaemon --max_exec_time=200'
)->everyFiveMinutes()
```

**Comment by garhbod** [comment]
Only gripe would be that there is no mention of `--max_exex_time` being seconds in the README

**Comment by orobogenius** [comment]
I'm glad you find the package helpful @garhbod.

About `--max-exec-time`, even though the README does exactly state `--max_exec_time` to be in seconds, it does provide a reference to [max_execution_time](http://php.net/manual/en/info.configuration.php#ini.max-execution-time). In the README, this value defaults to whatever the `max_execution_time` in your PHP runtime is, minus 5 seconds - `ini_get('max_execution_time') - 5s`.
