### ISSUE TITLE
Sansdaemon doesn't close the worker for delayed jobs. That is if the job is still in the future

### ISSUE THREAD

**Issue by davexoyinbo** [orobogenius/sansdaemon#15]

**Comment by orobogenius** [comment]
Yes @davexoyinbo, this is a bug that has also been pointed out by another user. The issue is not only limited to delayed jobs but also affects jobs that have been marshaled by the worker.

I'm working on a fix and will tag a new release when it's done. Thank you for also pointing this out.

**Comment by davexoyinbo** [comment]
Ok. Thanks.
