### ISSUE TITLE
hy i am not able to install this package through composer on laravel 5.8

### ISSUE THREAD

**Issue by dev-talha-anwar** [orobogenius/sansdaemon#23]
λ composer require queueworker/sansdaemon
Using version ^1.2 for queueworker/sansdaemon
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.37
    - Conclusion: don't install laravel/framework v5.8.37
    - queueworker/sansdaemon v1.2.0 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - queueworker/sansdaemon v1.2.1 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - queueworker/sansdaemon v1.2.2 requires illuminate/support ^6.0|^7.0 -> satisfiable by laravel/framework[6.x-dev, 7.x-dev], illuminate/support[6.x-dev, 7.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.2.0, v7.2.1, v7.2.2].
    - Can only install one of: laravel/framework[6.x-dev, v5.8.37].
    - Can only install one of: laravel/framework[7.x-dev, v5.8.37].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.1.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.10.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.11.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.12.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.13.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.13.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.14.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.15.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.15.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.16.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.17.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.17.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.18.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.18.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.18.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.2.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.3.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.4.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.5.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.5.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.5.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.6.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.6.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.6.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.7.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v6.8.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.3|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.4|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.5|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.6|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.7|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.0.8|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.1.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.1.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.1.2|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.1.3|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.2.0|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.2.1|don't install laravel/framework v5.8.37
    - don't install illuminate/support v7.2.2|don't install laravel/framework v5.8.37
    - Installation request for laravel/framework (locked at v5.8.37, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.37].
    - Installation request for queueworker/sansdaemon ^1.2 -> satisfiable by queueworker/sansdaemon[v1.2.0, v1.2.1, v1.2.2].

**Comment by orobogenius** [comment]
Hello @anwartalha, please install version 1.1.1 that supports Laravel 5.

```
composer require queueworker/sansdaemon:1.1.1
