### ISSUE TITLE
Is this package support Lumen?

### ISSUE THREAD

**Issue by adityadarma** [orobogenius/sansdaemon#27]
I get an error when using on lumen
Argument 2 passed to Queueworker\SansDaemon\SansDaemonServiceProvider::Queueworker\SansDaemon\{closure}() must be an instance of Illuminate\Contracts\Foundation\A  
  pplication, instance of Laravel\Lumen\Application given, called in /Applications/XAMPP/xamppfiles/htdocs/ecommerce-api/vendor/illuminate/container/Container.php o  
  n line 690

**Comment by orobogenius** [comment]
@adityadarma No, it does not support Lume.
