### ISSUE TITLE
The "--sansdaemon" option does not exist.

### ISSUE THREAD

**Issue by nickinguel** [orobogenius/sansdaemon#6]
After a fresh installation of this package, I typed in the terminal the recommended command 
`php artisan queue:work --sansdaemon` as said in the [README](https://packagist.org/packages/queueworker/sansdaemon), but I constantly got the following error : 
> The "--sansdaemon" option does not exist.

**Comment by orobogenius** [comment]
@cfass I can confirm that the command is working. After installation, once laravel auto-discovers the package, it'll work. If you're not using laravel 5.5 and above, you should add the service provider `Queueworker\SansDaemon\SansDaemonServiceProvider::class` to your `config/app.php` file.

It won't also hurt to run `composer dump-autoload`.

**Comment by nickinguel** [comment]
Sure I do use Laravel 5.5 but let me retry it after the `composer dump-autoload`. I'll be back.

**Comment by nickinguel** [comment]
It still doesn't work after `composer dump-autoload`. Have you ever tried on a different computer than yours?

**Comment by nickinguel** [comment]
I kind of "found" what was causing the problem. It is a kind of incompatibility with the Bugsnag library **Service provider app** presence in the `app.php` mentionned in the [Bugsnag installation process doc](https://docs.bugsnag.com/platforms/php/laravel/).

When we remove **Bugsnag service provider** inclusion from the `config/app.php` (`Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class`), everything goes the right way :
I mean, the `php artisan queue:work --sansdaemon` works properly but adding it back cause the same problem again.

I attached the `BugsnagServiceProvider` php file, so you can check for it to figure out what is causing incompatibility. Thank you.

[BugsnagServiceProvider.php.txt](https://github.com/orobogenius/sansdaemon/files/2754930/BugsnagServiceProvider.php.txt)

**Comment by orobogenius** [comment]
@cfass Thanks for bringing up the issue with Bugsnag, this definitely helped me narrow down the problem. I've fixed the issue and made a new release, you may now run composer update and use the package as normal.
